services:
  app:
    image: falaeittalent/falae-app
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - falae-net
    env_file:
      - ./.env
    volumes:
      - mysql-data:/var/lib/mysql
      - image-data:/images

  proxy:
    image: nginx:1.25.2-alpine
    depends_on:
      - app
    restart: unless-stopped
    container_name: proxy_falae
    volumes:
      - ./.docker/nginx/conf:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      - falae-net

  db:
    image: mysql:8.0.34
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - falae-net

networks:
  falae-net:

volumes:
  mysql-data:
  image-data:
