default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: <%= ENV['DB_USER'] || secrets.DB_USER %>
  password: <%= ENV['DB_PASSWORD'] || secrets.DB_PASSWORD %>
  database: <%= ENV['DB_NAME'] || secrets.DB_NAME %>
  port: <%= ENV['DB_PORT'] || secrets.DB_PORT %>
  host: <%= ENV['DB_HOST'] || secrets.DB_HOST %>

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: <%= ENV['DB_USERNAME'] || secrets.DB_USERNAME %>
  password: <%= ENV['DB_PASSWORD'] || secrets.DB_PASSWORD %>
  database: <%= ENV['DB_NAME'] || secrets.DB_NAME %>
  port: <%= ENV['DB_PORT'] || secrets.DB_PORT %>
  host: <%= ENV['DB_HOST'] || secrets.DB_HOST %>
