name: CD

on:
  push:
    branches:
      - ci-test-01
  #workflow_run:
    #workflows: CI
    #types:
      #- completed
  workflow_dispatch:

jobs:
  CD:
    #if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}

    steps:
      - name: Configure SSH AWS
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/aws-cloud.key
          chmod 600 ~/.ssh/aws-cloud.key
          cat >>~/.ssh/config <<END
          Host aws-cloud
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/aws-cloud.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.AWS_SSH_USER }}
          SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
          SSH_HOST: ${{ secrets.AWS_SSH_HOST }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy Docker
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          
          docker build . -t $DOCKER_USER/falae-app:latest 
          docker push $DOCKER_USER/falae-app:latest

          docker build . -t $DOCKER_USER/falae-nginx:latest
          docker push $DOCKER_USER/falae-nginx:latest

      - name: Clonning repository
        run: |
           ssh aws-cloud "sudo rm -Rf /home/ubuntu/falae"
           ssh aws-cloud "git clone -b ci-test-01 https://github.com/falae-it-talent/falae.git"

      - name: Create .env file
        run: |
            ssh aws-cloud "echo DB_USER=root > /home/ubuntu/falae/.env"
            ssh aws-cloud "echo DB_NAME=falae >> /home/ubuntu/falae/.env"
            ssh aws-cloud "echo DB_PASSWORD=falae@pass >> /home/ubuntu/falae/.env"
            ssh aws-cloud "echo DB_HOST=db >> /home/ubuntu/falae/.env"
            ssh aws-cloud "echo DB_PORT=3306 >> /home/ubuntu/falae/.env"
            ssh aws-cloud "echo RAILS_ENV=development >> /home/ubuntu/falae/.env"
            ssh aws-cloud "echo SENDGRID_APIKEY= >> /home/ubuntu/falae/.env"
            ssh aws-cloud "echo FALAE_IMAGES_PATH=/images >> /home/ubuntu/falae/.env"
            ssh aws-cloud "echo SECRET_KEY_BASE=82a79eb5d2a9eb072265d625817788d829c2203c7ff7ff6511b063cc5e38ab917738be87732c253f1b543064e793bd0715428be4e41622b1a9328bd8185e74dd >> /home/ubuntu/falae/.env"


      - name: Stop & Remove Docker Images and Containers
        run: |
          ssh aws-cloud "sudo docker compose down"
          ssh aws-cloud "sudo docker ps -qa | xargs docker rm -f"
          ssh aws-cloud "sudo docker images -qa | xargs docker rmi -f"
          ssh aws-cloud "sleep 10"


      - name: Pull latest Docker images
        run: |
          ssh aws-cloud "sudo docker compose -f /home/ubuntu/falae/docker-compose.yml pull"

      - name: Deploy Application
        run: |
          ssh aws-cloud "sudo docker compose -f /home/ubuntu/falae/docker-compose.yml up -d"
          ssh aws-cloud "sleep 20"
          ssh aws-cloud "cd /home/ubuntu/falae/ && sudo su && ./restoreDB.sh dump.sql"
