name: CD

on:
  push:
    branches:
      - ci-test-01
  workflow_dispatch:

jobs:
  CD:
    #if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}

    steps:
      - name: Configure SSH AWS
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/aws-cloud.key
          chmod 600 ~/.ssh/aws-cloud.key
          cat >>~/.ssh/config <<END
          Host aws-cloud
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/aws-cloud.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.AWS_SSH_USER }}
          SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
          SSH_HOST: ${{ secrets.AWS_SSH_HOST }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy Docker
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          
          docker build . -t $DOCKER_USER/falae-app:latest 
          docker push $DOCKER_USER/falae-app:latest

          docker build . -t $DOCKER_USER/falae-nginx:latest
          docker push $DOCKER_USER/falae-nginx:latest

      - name: Copy docker-compose.yml to the instance
        run: scp ./docker-compose.yml aws-cloud:/home/ubuntu/falae/

      - name: Stop & Remove Docker Images and Containers
        run: |
          ssh aws-cloud "cd /home/ubuntu/falae/ && sudo docker compose down --rmi all"
          ssh aws-cloud "sleep 10"

      - name: Pull latest Docker images
        run: |
          ssh aws-cloud "sudo docker compose -f /home/ubuntu/falae/docker-compose.yml pull"

      - name: Deploy Application
        run: |
          ssh aws-cloud "sudo docker compose -f /home/ubuntu/falae/docker-compose.yml up -d"
          ssh aws-cloud "sleep 20"
         
