name: CI

on:
  push:
    branches:
      - ci-test-01

jobs:  
  tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.34
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
          MYSQL_USER: ${{ secrets.DB_USER }}
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports: ["3306:3306"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
          
      - name: Check for missing gems
        run: bundle check || bundle install


      # - name: Setup test database
      #   env:
      #     RAILS_ENV: test
      #     DB_USER: ${{ secrets.DB_USER }}
      #     DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      #     DB_NAME: ${{ secrets.DB_NAME }}
      #     DB_PORT: ${{ secrets.DB_PORT }}
      #     DB_HOST: ${{ secrets.DB_HOST }}
      #   run: |
      #     bundle exec bin/rails db:setup

      - name: Run tests
        run: bundle exec bin/rspec
