name: CI

on:
  push:
    branches:
      - ci-test-01 
  workflow_dispatch:
    inputs:
      manual-trigger:
        description: 'Manual trigger for CI'
        default: 'Run CI'

jobs:
  CI-01:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.6'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Create and migrate database
        run: |
          bundle exec rails db:create RAILS_ENV=development
          bundle exec rails db:migrate RAILS_ENV=development

      - name: Run RSpec tests
        run: bundle exec rspec

