name: CI/CD
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_USER: root
      DB_PASSWORD: falae@pass
      DB_NAME: falae
      DB_PORT: 3306
      DB_HOST: db

    services:
      db:
        image: guilherme2041/falae-app
        env:
          MYSQL_ROOT_PASSWORD: falae@pass
          MYSQL_DATABASE: falae
        ports: ["3306:3306"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.6'

      - name: Install Yarn
        run: |
          sudo apt-get install -yqq nodejs
          npm install -g yarn

      - name: Set up environment variables
        run: |
          # Encode the password and store it in an environment variable
          export ENCODED_PASSWORD=$(echo -n 'falae@pass' | jq -s -R -r @uri)
        shell: bash

      - name: Build and run tests
        env:
          DATABASE_URL: "mysql2://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME"
          RAILS_ENV: test 
        run: |
          sudo apt-get -yqq install libmysqlclient-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake db:create
          bundle exec rake db:migrate
          bundle exec rspec .
