# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: CI/CD
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker Compose
        run: |
          sudo apt-get install -yqq docker-compose
          sudo docker-compose up -d
          # Wait for containers to be ready (you may need to adjust the sleep time)
          sleep 10

      - name: Restore Database
        run: |
          # Modify the following command based on your actual restore logic
          ./restoreDB.sh dump.sql

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.6

      - name: Install Yarn
        run: |
          sudo apt-get install -yqq nodejs
          npm install -g yarn

      - name: Build and run tests
        env:
          DATABASE_URL: mysql2://root:falae%40pass@db:3306/falae
          RAILS_ENV: development 
        run: |
          sudo apt-get -yqq install libmysqlclient-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake db:migrate
          bundle exec rspec .
