# .github/workflows/ruby.yml
name: Ruby

on:
  push:
    branches: [lucasarags-patch-1]
  pull_request:
    branches: [main]

env:
  MYSQL_DB: falae
  MYSQL_USER: root
  MYSQL_PASSWORD: falae@pass
  MYSQL_HOST: db
  MYSQL_PORT: 3306
  RAILS_ENV: test

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ${{ env.MYSQL_DB }}
          MYSQL_USER: ${{ env.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
        ports: ['3306:3306']
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.4
          bundler-cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get -yqq install default-libmysqlclient-dev
          bundle install --jobs 4 --retry 3
      - name: Run Tests
        env:
          DB_ADAPTER: mysql2
          DB_USERNAME: ${{ env.MYSQL_USER }}
          DB_PASSWORD: ${{ env.MYSQL_PASSWORD }}
          DB_DATABASE: ${{ env.MYSQL_DB }}
          DB_HOST: ${{ env.MYSQL_HOST }}
          DB_PORT: ${{ env.MYSQL_PORT }}
        run: |
          cp config/database.ci.yml config/database.yml
          bundle exec rails db:schema:load
          bundle exec rspec --format progress
