name: Test

on:
  push:
    branches: [ "lucasarags-patch-1" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
      with:
        ruby-version: '3.0.6'
        bundler-cache: true 

    - name: Install MySQL
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-server
        
    - name: Install Dependencies and Run Tests
      run: |
          bundle install --jobs 4 --retry 3
          bundle exec rake db:create db:migrate
          bundle exec rspec
