# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: CI/CD
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: guilherme2041/falae-app
        env:
          MYSQL_ROOT_PASSWORD: falae@pass # ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: root # ${{ secrets.DB_NAME }}
        ports: ["3306:3306"]
        # options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.6'

      - name: Install Yarn
        run: |
          sudo apt-get install -yqq nodejs
          npm install -g yarn

      - name: Set up environment variables
        run: |
          # Encode the password and store it in an environment variable
          export ENCODED_PASSWORD=$(echo -n 'falae@pass' | jq -s -R -r @uri)
        shell: bash
      - name: Build and run test
        env:
          DATABASE_URL: "mysql2://root:${{ env.ENCODED_PASSWORD }}@db:3306/falae"
          RAILS_ENV: test 
        run: |
          sudo apt-get -yqq install libmysqlclient-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake db:create
          bundle exec rake db:migrate
          bundle exec rspec .
