# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: CI/CD
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: guilherme2041/falae-app
        env:
          MYSQL_ROOT_PASSWORD: falae@pass # ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: root # ${{ secrets.DB_NAME }}
        ports: ["3306:3306"]
        # options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v2
        with:
          ruby-version: 3.0.6

      - name: Install Yarn
        run: |
          sudo apt-get install -yqq nodejs
          npm install -g yarn
      - name: Build and run tests
        env:
          DATABASE_URL: mysql2://root:falae@pass:db:3306:falae  # ${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}
          RAILS_ENV: development 
        run: |
          sudo apt-get -yqq install libmysqlclient-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake db:create
          bundle exec rake db:migrate
          bundle exec rspec .
